---
version: "3.9"
services:
  fullnode:
    image: mysten/sui-node:devnet-0.4.0
    ports:
    - "9000:9000"
    volumes:
    - ./fullnode-template.yaml:/opt/sui-node/fullnode.yaml:ro
    - ./genesis.blob:/opt/sui-node/genesis.blob:ro
    - suidb:/opt/sui-node/suidb
    command: ["/usr/local/bin/sui-node", "--config-path", "/opt/sui-node/fullnode.yaml"]
volumes:
  suidb:
